packages:
  - turbo
  - docs
  - packages/*
  - examples/*
  - packages/*/tests/fixture/*
  - packages/*/e2e/fixture/*

catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/compiler': ^2.12.2
  '@astrojs/internal-helpers': ^0.6.1
  '@astrojs/markdown-remark': ^6.3.3
  '@astrojs/mdx': ^4.3.1
  '@astrojs/node': ^9.3.0
  '@astrojs/preact': ^4.1.0
  '@astrojs/react': ^4.3.0
  '@astrojs/rss': ^4.0.12
  '@astrojs/sitemap': ^3.4.1
  '@astrojs/starlight': ~0.35.1
  '@astrojs/vercel': ^8.2.2
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.5
  '@croct/plug': ^0.18.1
  '@faker-js/faker': ^9.9.0
  '@fortawesome/fontawesome-free': ^6.7.2
  '@lunariajs/core': ^0.1.1
  '@nanostores/preact': ^1.0.0
  '@orama/wc-components': ^0.8.1
  '@playwright/test': ^1.54.1
  '@turbo/gen': ^2.5.5
  '@types/content-type': ^1.1.9
  '@types/debug': ^4.1.12
  '@types/hast': ^3.0.4
  '@types/lodash': ^4.17.20
  '@types/mdast': ^4.0.4
  '@types/node': ^24.0.15
  '@types/pako': ^2.0.3
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/unist': ^3.0.3
  '@types/xast': ^2.0.4
  '@vercel/analytics': ^1.5.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  ast-types: ^0.14.2
  astro: ^5.12.0
  astro-integration-kit: ~0.18.0
  content-type: ^1.0.5
  debug: ^4.4.1
  devalue: ^5.1.1
  estree-walker: ^3.0.3
  fast-glob: ^3.3.3
  husky: ^9.1.7
  jest-extended: ^6.0.0
  js-base64: ^3.7.7
  lint-staged: ^16.1.2
  lodash: ^4.17.21
  magic-string: ^0.30.17
  mdast-util-from-markdown: ^2.0.2
  nanostores: ^1.0.1
  pako: ^2.1.0
  postcss: ^8.5.6
  preact: ^10.26.9
  prettier: ^3.6.2
  prettier-plugin-astro: ^0.14.1
  react: ^19.1.0
  react-dom: ^19.1.0
  recast: ^0.23.11
  rehype: ^13.0.2
  rollup: ^4.45.1
  sharp: ^0.34.3
  shiki: ^3.8.1
  sitemap: ^8.0.0
  starlight-cooler-credit: ^0.4.0
  starlight-links-validator: ^0.17.0
  starlight-package-managers: ^0.11.0
  strip-ansi: ^7.1.0
  tsup: 8.5.0
  turbo: ^2.5.5
  typescript: ^5.8.3
  undici: ^7.12.0
  unist-util-is: ^6.0.0
  upath: ^2.0.1
  vite: ^7.0.5
  vitest: ^3.2.4
  zod: ^4.0.5

catalogMode: prefer

catalogs:
  lax:
    '@astrojs/starlight': '>=0.29 <0.32'
    astro: ^5
  min:
    astro: ^5
    astro-integration-kit: ~0.17 || ~0.18
    vite: ^4 || ^5 || ^6

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp

overrides:
  '@orama/core': 0.1.11
  astro: 'catalog:'
  picomatch: 3.0.1
  vite: 'catalog:'

patchedDependencies:
  astro: patches/astro.patch
