catalog:
  astro: ^4.14.2
  astro-integration-kit: ~0.16.0
  '@astrojs/compiler': ^2.10.3
  '@astrojs/sitemap': ^3.1.6
  '@astrojs/starlight': ^0.26.1
  '@types/debug': ^4.1.12
  '@types/node': ^22.4.0
  '@faker-js/faker': ^8.4.1
  '@lunariajs/core': ^0.1.1
  debug: ^4.3.6
  sitemap: ^8.0.0
  ast-types: ^0.14.2
  estree-walker: ^3.0.3
  magic-string: ^0.30.11
  recast: ^0.23.9
  upath: ^2.0.1
  tsup: 8.2.4
  typescript: ^5.5.4
  vite: ^5.4.1
  vitest: ^2.0.5
  '@vitest/ui': ^2.0.5
  '@vitest/coverage-v8': ^2.0.5
  jest-extended: ^4.0.2
catalogs:
  lax:
    astro: ^4
    '@astrojs/starlight': '>=0.16 <0.26'
  min:
    astro: ^4.12.2
    astro-integration-kit: ~0.16
    vite: ^4 || ^5
packages:
  - turbo
  - docs
  - packages/*
  - examples/*
