catalog:
  astro: ^5.2.3
  astro-integration-kit: ~0.18.0
  '@astrojs/compiler': ^2.10.3
  '@astrojs/sitemap': ^3.2.1
  '@astrojs/node': ^9.0.2
  '@astrojs/starlight': ~0.31
  '@astrojs/internal-helpers': ^0.5.0
  '@types/content-type': ^1.1.8
  '@types/debug': ^4.1.12
  '@types/hast': ^3.0.4
  '@types/node': ^22.12.0
  '@faker-js/faker': ^9.4.0
  '@lunariajs/core': ^0.1.1
  '@playwright/test': ^1.50.0
  content-type: ^1.0.5
  debug: ^4.4.0
  devalue: ^5.1.1
  sitemap: ^8.0.0
  ast-types: ^0.14.2
  estree-walker: ^3.0.3
  magic-string: ^0.30.17
  nanostores: ^0.11.3
  recast: ^0.23.9
  rehype: ^13.0.2
  upath: ^2.0.1
  tsup: 8.3.6
  typescript: ^5.7.3
  vite: ^6.0.11
  vitest: ^3.0.4
  '@vitest/ui': ^3.0.4
  '@vitest/coverage-v8': ^3.0.4
  jest-extended: ^4.0.2
catalogs:
  lax:
    astro: ^5
    '@astrojs/starlight': '>=0.29 <0.32'
  min:
    astro: ^5
    astro-integration-kit: ~0.17 || ~0.18
    vite: ^4 || ^5 || ^6
packages:
  - turbo
  - docs
  - packages/*
  - examples/*
  - packages/*/tests/fixture/*
  - packages/*/e2e/fixture/*
