catalog:
  astro: ^4.11.5
  astro-integration-kit: ^0.14.0
  '@astrojs/compiler': ^2.8.1
  '@astrojs/sitemap': ^3.1.4
  '@astrojs/starlight': ^0.25.0

  '@types/debug': ^4.1.12
  '@types/node': ^20.14.10

  '@faker-js/faker': ^8.4.1
  '@lunariajs/core': ^0.1.1
  debug: ^4.3.4
  sitemap: ^8.0.0

  ast-types: ^0.14.2
  estree-walker: ^3.0.3
  magic-string: ^0.30.10
  recast: ^0.23.7
  upath: ^2.0.1

  tsup: ^8.1.0
  typescript: ^5.5.3

  vite: ^5.3.3
  vitest: ^2.0.2
  '@vitest/ui': ^2.0.2
  '@vitest/coverage-v8': ^2.0.2
  jest-extended: ^4.0.2

catalogs:
  min:
    astro: ^4.3.5
    astro-integration-kit: ~0.14
    vite: ^4 || ^5

packages:
  - turbo
  - docs
  - 'packages/*'
  - 'examples/*'
