packages:
  - turbo
  - docs
  - packages/*
  - examples/*
  - packages/*/tests/fixture/*
  - packages/*/e2e/fixture/*
catalog:
  '@astrojs/compiler': ^2.12.2
  '@astrojs/internal-helpers': ^0.6.1
  '@astrojs/node': ^9.3.0
  '@astrojs/sitemap': ^3.4.1
  '@astrojs/starlight': ~0.35.0
  '@faker-js/faker': ^9.9.0
  '@lunariajs/core': ^0.1.1
  '@playwright/test': ^1.54.1
  '@types/content-type': ^1.1.9
  '@types/debug': ^4.1.12
  '@types/hast': ^3.0.4
  '@types/node': ^24.0.14
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  ast-types: ^0.14.2
  astro: ^5.11.2
  astro-integration-kit: ~0.18.0
  content-type: ^1.0.5
  debug: ^4.4.1
  devalue: ^5.1.1
  estree-walker: ^3.0.3
  jest-extended: ^6.0.0
  magic-string: ^0.30.17
  nanostores: ^1.0.1
  recast: ^0.23.11
  rehype: ^13.0.2
  rollup: ^4.45.1
  sitemap: ^8.0.0
  tsup: 8.5.0
  typescript: ^5.8.3
  upath: ^2.0.1
  vite: ^7.0.4
  vitest: ^3.2.4
catalogs:
  lax:
    '@astrojs/starlight': '>=0.29 <0.32'
    astro: ^5
  min:
    astro: ^5
    astro-integration-kit: ~0.17 || ~0.18
    vite: ^4 || ^5 || ^6
