catalog:
  astro: ^5.6.1
  astro-integration-kit: ~0.18.0
  '@astrojs/compiler': ^2.11.0
  '@astrojs/sitemap': ^3.3.0
  '@astrojs/node': ^9.1.3
  '@astrojs/starlight': ~0.32.6
  '@astrojs/internal-helpers': ^0.6.1
  '@types/content-type': ^1.1.8
  '@types/debug': ^4.1.12
  '@types/hast': ^3.0.4
  '@types/node': ^22.14.0
  '@faker-js/faker': ^9.6.0
  '@lunariajs/core': ^0.1.1
  '@playwright/test': ^1.51.1
  content-type: ^1.0.5
  debug: ^4.4.0
  devalue: ^5.1.1
  sitemap: ^8.0.0
  ast-types: ^0.14.2
  estree-walker: ^3.0.3
  magic-string: ^0.30.17
  nanostores: ^0.11.4
  recast: ^0.23.11
  rehype: ^13.0.2
  upath: ^2.0.1
  tsup: 8.4.0
  typescript: ^5.8.3
  vite: ^6.2.5
  rollup: ^4.34.6
  vitest: ^3.1.1
  '@vitest/ui': ^3.1.1
  '@vitest/coverage-v8': ^3.1.1
  jest-extended: ^4.0.2
catalogs:
  lax:
    astro: ^5
    '@astrojs/starlight': '>=0.29 <0.32'
  min:
    astro: ^5
    astro-integration-kit: ~0.17 || ~0.18
    vite: ^4 || ^5 || ^6
packages:
  - turbo
  - docs
  - packages/*
  - examples/*
  - packages/*/tests/fixture/*
  - packages/*/e2e/fixture/*
