packages:
  - turbo
  - docs
  - packages/*
  - examples/*
  - packages/*/tests/fixture/*
  - packages/*/e2e/fixture/*
  - packages/*/e2e/fixture/partials/*

catalog:
  '@astrojs/check': ^0.9.7-beta.1
  '@astrojs/cloudflare': ^13.1.4
  '@astrojs/compiler': ^3.0.1
  '@astrojs/internal-helpers': ^0.8.0
  '@astrojs/markdown-remark': ^7.0.1
  '@astrojs/mdx': ^5.0.2
  '@astrojs/node': ^10.0.3
  '@astrojs/preact': ^5.0.2
  '@astrojs/react': ^5.0.1
  '@astrojs/rss': ^4.0.15-beta.4
  '@astrojs/sitemap': ^3.6.1-beta.3
  '@astrojs/starlight': ~0.38.2
  '@astrojs/vercel': ^10.0.2
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@croct/plug': ^0.23.0
  '@faker-js/faker': ^10.3.0
  '@fortawesome/fontawesome-free': ^7.2.0
  '@lunariajs/core': ^0.1.1
  '@mermaid-js/mermaid-cli': ^11.12.0
  '@nanostores/preact': ^1.0.0
  '@orama/wc-components': ^0.8.1
  '@playwright/test': ^1.58.2
  '@sparticuz/chromium': ^143.0.4
  '@turbo/gen': ^2.8.12
  '@types/content-type': ^1.1.9
  '@types/debug': ^4.1.12
  '@types/hast': ^3.0.4
  '@types/lodash': ^4.17.24
  '@types/mdast': ^4.0.4
  '@types/node': ^25.3.3
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/unist': ^3.0.3
  '@types/xast': ^2.0.4
  '@vercel/analytics': ^1.6.1
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/ui': ^4.0.18
  ast-types: ^0.14.2
  astro: ^6.0.8
  astro-integration-kit: ~0.20.0
  content-type: ^1.0.5
  debug: ^4.4.3
  devalue: ^5.6.3
  estree-walker: ^3.0.3
  fast-glob: ^3.3.3
  husky: ^9.1.7
  jest-extended: ^7.0.0
  lint-staged: ^16.3.1
  lodash: ^4.17.23
  magic-string: ^0.30.21
  mdast-util-from-markdown: ^2.0.3
  mermaid: ^11.13.0
  nanostores: ^1.1.1
  postcss: ^8.5.6
  preact: ^10.28.4
  prettier: ^3.8.1
  prettier-plugin-astro: ^0.14.1
  puppeteer: ^24.40.0
  puppeteer-core: ^24.40.0
  react: ^19.2.4
  react-dom: ^19.2.4
  recast: ^0.23.11
  rehype: ^13.0.2
  rollup: ^4.59.0
  sharp: ^0.34.5
  shiki: ^4.0.0
  sitemap: ^9.0.1
  starlight-cooler-credit: ^0.6.0
  starlight-links-validator: ^0.20.1
  starlight-package-managers: ^0.12.0
  strip-ansi: ^7.2.0
  tsup: 8.5.1
  turbo: ^2.8.12
  typescript: ^5.9.3
  undici: ^7.22.0
  unist-util-is: ^6.0.1
  upath: ^2.0.1
  vite: ^7.3.1
  vitest: ^4.0.18
  wrangler: ^4.77.0
  zod: ^4.3.6

catalogMode: prefer

catalogs:
  lax:
    '@astrojs/starlight': ^0.38.0
    astro: ^6
  min:
    astro: ^6
    astro-integration-kit: ^0.20
    vite: ^7

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - puppeteer
  - sharp

overrides:
  '@orama/core': 0.1.11
  astro: 'catalog:'
  astro-integration-kit: 'catalog:'
  picomatch: 3.0.1
  puppeteer: 'catalog:'
  vite: 'catalog:'

patchedDependencies:
  astro: patches/astro.patch
