packages:
  - turbo
  - docs
  - packages/*
  - examples/*
  - packages/*/tests/fixture/*
  - packages/*/e2e/fixture/*
  - packages/*/e2e/fixture/partials/*

catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/compiler': ^2.13.1
  '@astrojs/internal-helpers': ^0.7.5
  '@astrojs/markdown-remark': ^6.3.10
  '@astrojs/mdx': ^4.3.13
  '@astrojs/node': ^9.5.2
  '@astrojs/preact': ^4.1.3
  '@astrojs/react': ^4.4.2
  '@astrojs/rss': ^4.0.15
  '@astrojs/sitemap': ^3.7.0
  '@astrojs/starlight': ~0.37.6
  '@astrojs/vercel': ^9.0.4
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@croct/plug': ^0.21.0
  '@faker-js/faker': ^10.3.0
  '@fortawesome/fontawesome-free': ^7.1.0
  '@lunariajs/core': ^0.1.1
  '@nanostores/preact': ^1.0.0
  '@orama/wc-components': ^0.8.1
  '@playwright/test': ^1.58.2
  '@turbo/gen': ^2.8.3
  '@types/content-type': ^1.1.9
  '@types/debug': ^4.1.12
  '@types/hast': ^3.0.4
  '@types/lodash': ^4.17.23
  '@types/mdast': ^4.0.4
  '@types/node': ^25.2.2
  '@types/pako': ^2.0.4
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  '@types/unist': ^3.0.3
  '@types/xast': ^2.0.4
  '@vercel/analytics': ^1.6.1
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/ui': ^4.0.18
  ast-types: ^0.14.2
  astro: ^5.17.1
  astro-integration-kit: ~0.19.1
  content-type: ^1.0.5
  debug: ^4.4.3
  devalue: ^5.6.2
  estree-walker: ^3.0.3
  fast-glob: ^3.3.3
  husky: ^9.1.7
  jest-extended: ^7.0.0
  js-base64: ^3.7.8
  lint-staged: ^16.2.7
  lodash: ^4.17.23
  magic-string: ^0.30.21
  mdast-util-from-markdown: ^2.0.2
  nanostores: ^1.1.0
  pako: ^2.1.0
  postcss: ^8.5.6
  preact: ^10.28.3
  prettier: ^3.8.1
  prettier-plugin-astro: ^0.14.1
  react: ^19.2.4
  react-dom: ^19.2.4
  recast: ^0.23.11
  rehype: ^13.0.2
  rollup: ^4.57.1
  sharp: ^0.34.5
  shiki: ^3.22.0
  sitemap: ^9.0.0
  starlight-cooler-credit: ^0.5.0
  starlight-links-validator: ^0.19.2
  starlight-package-managers: ^0.12.0
  strip-ansi: ^7.1.2
  tsup: 8.5.1
  turbo: ^2.8.3
  typescript: ^5.9.3
  undici: ^7.21.0
  unist-util-is: ^6.0.1
  upath: ^2.0.1
  vite: ^7.3.1
  vitest: ^4.0.18
  zod: ^4.3.6

catalogMode: prefer

catalogs:
  lax:
    '@astrojs/starlight': ^0.31.1
    astro: ^5
  min:
    astro: ^5
    astro-integration-kit: ^0.18 || ^0.19
    vite: ^5 || ^6 || ^7

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp

overrides:
  '@orama/core': 0.1.11
  astro: 'catalog:'
  astro-integration-kit: 'catalog:'
  picomatch: 3.0.1
  vite: 'catalog:'

patchedDependencies:
  astro: patches/astro.patch
