name: Publish Any Commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # Version will be inferred from package.json

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm run build

      - name: Publish Preview Release
        run: pnpx pkg-pr-new publish --pnpm ./packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
